#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID(s) of the running 4-to_infinity_and_beyond script
pid=$(pgrep -f "./4-to_infinity_and_beyond")

# If a PID was found, kill the process
if [ -n "$pid" ]; then
    kill "$pid"
fi
